project:
  title: "CLMS Documentation"

editor: visual

# Disable browser interaction
preview:
  browser: false  # Ensure no browser is triggered
  port: 8888      # Default port (shouldn't be used if the browser is disabled)

chrome: null       # Explicitly set to null to avoid using Chrome or any browser

format:
  html:
    toc: true  # Include a table of contents
    toc-depth: 2  # Limit the table of contents depth to 2 levels
    code-fold: true  # Enable code folding for code blocks
    theme: flatly  # Specify a theme (e.g., flatly, cosmo, cerulean)
  pdf:
    engine: pdflatex  # or xelatex if preferred
    toc: true
    number-sections: true
    documentclass: scrartcl  # Use a document class compatible with fonts
    fontsize: 12pt  # Set the default font size (optional)
    mainfont: "Arial"  # Specify the main font
    sansfont: "Arial"  # Specify the sans-serif font
    monofont: "Arial"  # Specify the monospaced font
    geometry: "margin=1in"  # Set page margins (optional)
  docx:
    toc: true

