name: Deploy to GitHub Pages

on:
  push:
    branches:
      - gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        npm install

    - name: Build and deploy
      run: |
        npm run build
        git add -A
        git commit -m "Deploy updates"
        git push origin gh-pages
